Repository WebUI-Project-Based-07-nr/Client, pull requests merged in 2024-07, with the labels that each got.

#68 SonarCloud Integration Client
  .github/workflows/main.yaml
  sonar-project.properties
Labels: Frontend part, feature

#77 #36 added close model when clicking outside
  src/components/popup-dialog/PopupDialog.tsx
Labels: Frontend part, bug, sprint 2

#76 Test/61/question editor component
  src/components/question-editor/QuestionEditor.tsx
  src/tests/unit/components/question-editor/QuestionEditor.spec.jsx
Labels: Frontend part, sprint 2, test

#92 #36 fixing; remove my part, login modal pop up when clicking outside …
  src/components/popup-dialog/PopupDialog.tsx
Labels: bug

#116 #95 added email verified notification modal window
  src/containers/guest-home-page/email-verified-notification/EmailVerifiedNotification.jsx
  src/containers/guest-home-page/email-verified-notification/EmailVerifiedNotification.styles.js
Labels: Frontend part, feature, sprint 3

#119 Email Confirmation Pop Up
  src/containers/guest-home-page/email-confirmation-popup/EmailConfirmationPopUp.jsx
  src/containers/guest-home-page/email-confirmation-popup/EmailConfirmationPopUp.styles.js
Labels: Frontend part, feature, sprint 3

#127 #101 added handele adding and deletion chips
  src/containers/tutor-home-page/subjects-step/SubjectsStep.jsx
Labels: Frontend part, feature, sprint 3

#123 test/121/write-test-for-app-btn
  src/tests/unit/components/app-button/AppButton.spec.jsx
Labels: Frontend part, test

#140 Feature/107/create a pop up window with sign up fields
  src/containers/guest-home-page/WhatCanYouDo.tsx
  src/tests/unit/containers/guest-home-page/what-can-you-do/WhatCanYouDo.spec.jsx
Labels: feature, sprint 3

#129 Feature/109/implement chips at subjects step
  src/components/app-select/AppSelect.styles.ts
  src/components/app-select/AppSelect.tsx
  src/components/popup-dialog/PopupDialog.tsx
  src/components/title-with-description/TitleWithDescription.tsx
  src/constants/translations/en/common.json
  src/constants/translations/en/footer.json
  src/constants/translations/en/signup.json
  src/containers/guest-home-page/WhatCanYouDo.tsx
  src/containers/guest-home-page/email-confirmation-popup/EmailConfirmationPopUp.jsx
  src/containers/guest-home-page/email-confirmation-popup/EmailConfirmationPopUp.styles.js
  src/containers/guest-home-page/email-verified-notification/EmailVerifiedNotification.jsx
  src/containers/guest-home-page/email-verified-notification/EmailVerifiedNotification.styles.js
  src/containers/guest-home-page/signup-dialog/SignupDialog.jsx
  src/containers/guest-home-page/signup-dialog/SignupDialog.styles.js
  src/containers/guest-home-page/signup-form/SignupForm.jsx
  src/containers/guest-home-page/signup-form/SignupForm.styles.js
  src/containers/tutor-home-page/subjects-step/SubjectsStep.jsx
  src/containers/tutor-home-page/subjects-step/SubjectsStep.styles.js
  src/tests/unit/components/app-button/AppButton.spec.jsx
  src/tests/unit/components/slider-with-input/SliderWithInput.spec.jsx
  src/tests/unit/components/user-steps-wrapper/UserStepsWrapper.spec.jsx
  src/tests/unit/containers/guest-home-page/what-can-you-do/WhatCanYouDo.spec.jsx
  src/tests/unit/pages/subjects/SubjectsStep.spec.jsx
  src/utils/validations/common.ts
Labels: Frontend part, feature, sprint 3
