Repository WebUI-Project-Based-07-nr/Client, pull requests merged in 2024-08, with the labels that each got.

#185 Bugfix/130/fix eslint errors
  .github/workflows/main.yaml
  src/constants/request.ts
  src/containers/add-resources/AddResources.tsx
  src/containers/my-quizzes/create-or-edit-quiz-container/CreateOrEditQuizContainer.tsx
  src/containers/my-resources/create-or-edit-question-modal/CreateOrEditQuestionModal.tsx
  src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx
  src/services/resource-service.ts
  src/tests/unit/components/enhanced-table/enhanced-table-pagination/EnhancedTablePagination.spec.jsx
  src/tests/unit/components/slider-with-input/SliderWithInput.spec.jsx
  src/types/common/types/common.types.ts
  src/types/index.ts
  src/types/my-resources/enum/myResources.enum.ts
  src/types/quizzes/interfaces/quizzes.interface.ts
  src/types/quizzes/quizzes.index.ts
Labels: bug

#173 Feature/164/implement offer card
  src/components/author-profile-name/AuthorProfileName.styles.ts
  src/components/author-profile-name/AuthorProfileName.tsx
  src/components/author-profile-name/mockValues.ts
  src/components/author-profile-picture/AuthorProfilePicture.styles.ts
  src/components/author-profile-picture/AuthorProfilePicture.tsx
  src/components/author-profile-picture/temp.svg
  src/components/author-profile-rating/AuthorProfileRating.styles.ts
  src/components/author-profile-rating/AuthorProfileRating.tsx
  src/components/author-profile-rating/mockValues.ts
  src/components/offer-buttons/OfferButtons.styles.ts
  src/components/offer-buttons/OfferButtons.tsx
  src/components/offers-title/OffersTitle.style.ts
  src/components/offers-title/OffersTitle.tsx
  src/components/offers-title/mockValues.ts
  src/components/price-per-hour/PricePerHour.style.ts
  src/components/price-per-hour/PricePerHour.tsx
  src/components/price-per-hour/mockValues.ts
  src/components/spoken-languages/SpokenLanguages.style.ts
  src/components/spoken-languages/SpokenLanguages.tsx
  src/components/spoken-languages/mockValues.ts
  src/components/study-subjects-chips/StudySubjectsChips.style.ts
  src/components/study-subjects-chips/StudySubjectsChips.tsx
  src/components/study-subjects-chips/mockValues.ts
  src/constants/translations/en/index.ts
  src/constants/translations/en/offer-details.json
  src/constants/translations/ua/index.ts
  src/constants/translations/ua/offer-details.json
  src/pages/find-offers/FindOffers.tsx
  src/pages/offer-details/OfferDetails.styles.ts
  src/pages/offer-details/OfferDetails.tsx
Labels: Frontend part, feature, sprint 4

#159 bug/158/fix-link-for-subjects-page
  src/pages/subjects/Subjects.tsx
Labels: Frontend part, bug, sprint 4

#194 Stepper Location
  src/components/user-steps-wrapper/UserStepsWrapper.tsx
  src/constants/request.ts
  src/containers/tutor-home-page/general-info-step/GeneralInfoStep.jsx
  src/context/location-context.tsx
  src/services/location-service.ts
  src/types/index.ts
  src/types/location/interfaces/location.interface.ts
  src/types/location/location.index.ts
Labels: Frontend part, feature, sprint 2

#206 Configured Sonar Code Coverage
  .github/workflows/main.yaml
  sonar-project.properties
Labels: Frontend part, feature

#205 Offer service
  src/constants/request.ts
  src/services/offer-service.ts
  src/types/offer/interfaces/offer.interfaces.ts
Labels: Frontend part, feature, sprint 5

#177 feature/166/Add-view-switcher
  src/components/toggle-button/ToggleButtons.tsx
  src/pages/find-offers/FindOffers.tsx
Labels: Frontend part, feature, sprint 5

#188 #179 complete grid
  src/containers/offer-cards/OfferCards.style.ts
  src/containers/offer-cards/OfferCards.tsx
Labels: Frontend part, feature, sprint 4

#219 Bugfix/218/popular categories eslint fix
  src/components/popular-categories/PopularCategories.styles.ts
  src/components/popular-categories/PopularCategories.tsx
Labels: bug, sprint 5

#175 feature/165/find-offer-sort-menu
  src/components/sort-menu/SortMenu.tsx
  src/pages/find-offers/FindOffers.tsx
Labels: Frontend part, feature, sprint 5

#221 Fixed FindOffer lint
  src/pages/find-offers/FindOffers.tsx
Labels: Frontend part, bug, sprint 5

#135 test/126/write-test-for-App-card
  src/tests/unit/components/app-card/AppCard.spec.jsx
Labels: Frontend part, test

#213 Feature/203/connect offers page with backend
  src/components/author-profile-name/AuthorProfileName.tsx
  src/components/author-profile-name/mockValues.ts
  src/components/author-profile-picture/AuthorProfilePicture.tsx
  src/components/author-profile-rating/AuthorProfileRating.tsx
  src/components/author-profile-rating/mockValues.ts
  src/components/offers-title/OffersTitle.tsx
  src/components/offers-title/mockValues.ts
  src/components/price-per-hour/PricePerHour.tsx
  src/components/spoken-languages/SpokenLanguages.tsx
  src/components/study-subjects-chips/StudySubjectsChips.tsx
  src/components/study-subjects-chips/mockValues.ts
  src/containers/offer-cards/OfferCards.tsx
  src/pages/find-offers/FindOffers.tsx
  src/pages/offer-details/OfferDetails.tsx
  src/types/offer/interfaces/offer.interfaces.ts
Labels: Frontend part, feature, sprint 5

#237 upd user service(image)
  src/constants/request.ts
  src/services/user-service.tsx
  src/types/user/user-interfaces/user.interfaces.ts
Labels: feature, sprint 6

#239 added student tutor switcher; upd fetch logic in offer cards
  src/containers/offer-cards/OfferCards.tsx
  src/pages/find-offers/FindOffers.tsx
  src/services/offer-service.ts
  src/tests/unit/pages/find-offers/FindOffers.spec.jsx
  src/types/offer/interfaces/offer.interfaces.ts
Labels: Frontend part, feature, sprint 6

#223 test/201/test-toggle-btn
  src/tests/unit/components/toggle-button/ToggleButtons.spec.jsx
Labels: Frontend part, test, sprint 5

#251 add popular categories;added in home tutor,student page and offer page
  src/components/popular-categories/PopularCategories.styles.ts
  src/components/popular-categories/PopularCategories.tsx
  src/pages/categories/DynamicIcon.jsx
  src/pages/find-offers/FindOffers.tsx
  src/pages/student-home/StudentHome.tsx
  src/pages/tutor-home/TutorHome.tsx
  src/types/categories/interfaces/categories.interfaces.ts
  src/types/common/interfaces/common.interfaces.ts
  src/types/common/types/common.types.ts
Labels: Frontend part, feature, sprint 6

#253 Bugfix/fix home routes student and tutor
  src/containers/layout/navbar/NavBar.tsx
  src/router/helpers/HomeRoute.tsx
  src/tests/unit/router/helpers/HomeRoute.spec.jsx
Labels: bug

#263 Improved UI for Location
  src/containers/tutor-home-page/general-info-step/GeneralInfoStep.jsx
  src/containers/tutor-home-page/general-info-step/GeneralInfoStep.styles.js
  src/utils/filter-options.ts
Labels: Frontend part, feature, sprint 6

#266 Bugfix/265/fix email confirmation
  src/constants/request.ts
  src/containers/email-confirm-modal/EmailConfirmModal.jsx
  src/containers/guest-home-page/email-confirmation-popup/EmailConfirmationPopUp.jsx
  src/index.tsx
  src/services/auth-service.ts
  src/tests/unit/containers/email-confirm-modal/EmailConfirmModal.spec.jsx
Labels: Frontend part, bug, sprint 6

#230 test/224/sort-menu-btn-test
  src/tests/unit/components/sort-menu/SortMenu.spec.jsx
Labels: Frontend part, test, sprint 5
